//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BotQueue
    {
        public int BotQueueId { get; set; }
        public int QueueDirection { get; set; }
        public int ChatId { get; set; }
        public string MessageText { get; set; }
        public bool IsCompleted { get; set; }
        public System.DateTime Date { get; set; }
    }
}
