//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotificationItem()
        {
            this.NotificationItemsLogs = new HashSet<NotificationItemsLog>();
            this.NotificationItemsLogLatests = new HashSet<NotificationItemsLogLatest>();
            this.RelatedNotifications = new HashSet<RelatedNotification>();
            this.RelatedNotifications1 = new HashSet<RelatedNotification>();
        }
    
        public int NotificationId { get; set; }
        public int ItemId { get; set; }
        public int NotificationType { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> High { get; set; }
        public string NotificationMsg { get; set; }
        public Nullable<int> Priority { get; set; }
    
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationItemsLog> NotificationItemsLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationItemsLogLatest> NotificationItemsLogLatests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedNotification> RelatedNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedNotification> RelatedNotifications1 { get; set; }
    }
}
