//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationItemsLogLatest
    {
        public int NotificationLogLatestId { get; set; }
        public int NotificationId { get; set; }
        public bool Value { get; set; }
        public System.DateTime Time { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual NotificationItem NotificationItem { get; set; }
    }
}
