//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationOccur
    {
        public NotificationOccur()
        {
            this.NotificationOccurUsers = new HashSet<NotificationOccurUser>();
        }
    
        public int OccurId { get; set; }
        public int NotificationId { get; set; }
        public System.DateTime DateOccured { get; set; }
        public bool IsDismissed { get; set; }
        public Nullable<System.DateTime> DateDismissed { get; set; }
        public bool IsAcknowledged { get; set; }
        public Nullable<System.DateTime> DateAcknowledged { get; set; }
        public Nullable<int> UserIdAcknowledged { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<NotificationOccurUser> NotificationOccurUsers { get; set; }
    }
}
