//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationItem
    {
        public NotificationItem()
        {
            this.NotificationItemsLogs = new HashSet<NotificationItemsLog>();
            this.NotificationItemsLogLatests = new HashSet<NotificationItemsLogLatest>();
        }
    
        public int NotificationId { get; set; }
        public int ItemId { get; set; }
        public int NotificationType { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> High { get; set; }
        public string NotificationMsg { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ICollection<NotificationItemsLog> NotificationItemsLogs { get; set; }
        public virtual ICollection<NotificationItemsLogLatest> NotificationItemsLogLatests { get; set; }
    }
}
