//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationOccurUser
    {
        public int OccurUserId { get; set; }
        public int OccurId { get; set; }
        public Nullable<System.DateTime> DateAcknowledged { get; set; }
        public string ReasonOccured { get; set; }
    
        public virtual NotificationOccur NotificationOccur { get; set; }
    }
}
