//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationItemsLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotificationItemsLog()
        {
            this.NotificationBots = new HashSet<NotificationBot>();
        }
    
        public int NotificationLogId { get; set; }
        public int NotificationId { get; set; }
        public bool Value { get; set; }
        public System.DateTime Time { get; set; }
        public byte[] TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationBot> NotificationBots { get; set; }
        public virtual NotificationItem NotificationItem { get; set; }
    }
}
