//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpcBooleanCommand
    {
        public int Id { get; set; }
        public string Location { get; set; }
        public bool CommandValue { get; set; }
        public int Interval { get; set; }
        public Nullable<System.DateTime> PreviousRun { get; set; }
    }
}
