//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.UsersServicesPermissions = new HashSet<UsersServicesPermission>();
        }
    
        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
    
        public virtual ICollection<UsersServicesPermission> UsersServicesPermissions { get; set; }
    }
}
