//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab
    {
        public Tab()
        {
            this.TabsItems = new HashSet<TabsItem>();
        }
    
        public int TabId { get; set; }
        public string TabName { get; set; }
    
        public virtual ICollection<TabsItem> TabsItems { get; set; }
    }
}
