//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Bots = new HashSet<Bot>();
            this.UsersItemsPermissions = new HashSet<UsersItemsPermission>();
            this.UsersServicesPermissions = new HashSet<UsersServicesPermission>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<Bot> Bots { get; set; }
        public virtual ICollection<UsersItemsPermission> UsersItemsPermissions { get; set; }
        public virtual ICollection<UsersServicesPermission> UsersServicesPermissions { get; set; }
    }
}
